### PR TITLE
Feature/rel

### LINKED ISSUE #15: Relationships visualization
**Is your feature request related to a problem? Please describe.**
I can see my nodes, but not the relationships between them. 

**Describe the solution you'd like**
Would be nice to have the possibility to display relationships between nodes.

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by nikita03565**
closes #15 
New PR that adds relationships visualization addressing review comments from https://github.com/stellasia/neomap/pull/93
I'd appreciate a review but if not i'm ready to merge it on my own.

Advanced queries supported:
image

Added arrowheads to display relationship directions:
image

The same thing with nodes:
image

Hiding relationships option for point layer type:
image

### CODE REVIEW

**Comment by stellasia** [comment]
Haven't tested but reading the code it looks good to me. Think you can go ahead and merge. Awesome contribution :)

**Comment by nikita03565** [comment]
ah sorry i should've clicked at squash and merge

**Comment by krishnapraveen7** [comment]
I can't see relationships option when I am in advanced query. Can someone help me with this?

**Comment by stellasia** [comment]
Hey @krishnapraveen7 ,

Unfortunately this feature has never been released due to a lack of time to maintain the project. I'll try and create a tarball if you want to give it a try, but I won't be able to create an official release anytime soon (would require more tests).

**Comment by stellasia** [comment]
Can't attach the tarball here, format is not supported... 

I have uploaded here for now: https://drive.google.com/file/d/1GOoY97XfjsrCDKfuEA3t3CZoSRHuvDgW/view?usp=sharing 
(to future users reading this, this link is not expected to be valid forever)

Be aware this is a development version, not well tested, so some bugs and regressions are possible, but the relationship feature is there.

**Pull request merged**
