### PR TITLE
Start tests

### PR DESCRIPTION
**Pull request by edumoreira1506**
Hello! I saw the issue #23 and I want to help you to do this tests! In this PR I have installed the enzyme and enzyme adapter for help us on components tests. And I did some tests too for start! I hope that helps :)

### CODE REVIEW

**Comment by stellasia** [comment]
Hi @edumoreira1506 , that's awesome! I'll take a quick look to understand how this works.

**Comment by edumoreira1506** [comment]
Sure! If you have some doubt, I am here :)

**Comment by stellasia** [comment]
Hi @edumoreira1506 , I only have one question/concern: the dependencies added only for tests, shouldn't they be in `devDependencies`  in `package.json` ? Thanks.

**Comment by edumoreira1506** [comment]
@stellasia Sure! I forgot this, but now it's fixed!

**Comment by stellasia** [comment]
@edumoreira1506 awesome! Thank you very much for putting this in place! I probably need to define more precise test cases now, but it's already a relief to have those ones!

**Pull request merged**
